a = input("Digite algo: ")
print("O tipo primitivo desse valor é: ", type(a))
print("É númerico?: ", a.isnumeric())
print("Tem espaço?: ", a.isspace())
print("É alfabético?: ", a.isalpha())
print("É alfanumérico?: ", a.isalnum())
print("Está em maiúsculas?: ", a.isupper())
print("Está em minúsculas?: ", a.islower())
print("Está capitalizadaw: ", a.istitle())